### ISSUE TITLE
panic runtime error: Backdoor.Win32.Agent.dppm.6c5018c81e9227cee423f647f0066e04

### ISSUE THREAD

**Issue by Meowoverflow** [MennaEssa/binee#13]
- Error msg : panic: runtime error: slice bounds out of range [:4096] with capacity 3602
- Error file: pefile.go
- Error function : 
``` golang
func analyzePeFile(data []byte, pe *PeFile) error {
        //code .......
        var headersSize uint32
	if pe.PeType == Pe32 {
		headersSize = pe.OptionalHeader.(*OptionalHeader32).SizeOfHeaders
	} else {
		headersSize = pe.OptionalHeader.(*OptionalHeader32P).SizeOfHeaders

	}
}
```
- Reason: SizeOfHeaders in OptionalHeader section is bigger than file size.
- Note: the file runs on windows without error.

**Comment by mmn3mm** [comment]
I will be working on this issue since @Meowoverflow is currently busy with the facts.

**Comment by mmn3mm** [comment]
### Fixed

The variable headersSize was used to get the first section to make it available if a malware uses code caves in headers to store required data for loading (imports for instance), so I did a temporary fix until we refactor the whole section thing by making the header section starts from 0 to the offset of the first section.
```go
var headersSize uint32
headersSize=math.MaxUint32
for _,section:=range pe.Sections{
	if section.Offset<headersSize{
		headersSize=section.Offset
	}
}
````
