### ISSUE TITLE
Running 32-bit PEs on x64 host (using SysWOW64 DLLs)

### ISSUE THREAD

**Issue by 0xbahaa** [MennaEssa/binee#8]
## Summary:
1- At first, running 32-bit PE files on 64-bit hosts would fail; because Binee was using the DLLs from `C:\Windows\System32` , and those are 64-bit DLLs.

2- But if the user supplied his own 32-bit DLLs using `-r` switch, it would work fine.
``` coffee
C:\Users\binbin\Desktop\work\binee\build>debugging_binee.exe  -r "C:\Users\binbin\Desktop\work\win10_32" ..\tests\ConsoleApplication1_x86.exe
[1] 0x210e82f0: F GetSystemTimeAsFileTime(lpSystemTimeAsFileTime = 0xb7feffe0) = 0xb7feffe0
[1] 0x210e6e70: P GetCurrentThreadId() = 0x0
...
[1] 0x20110690: P GetCurrentProcess() = 0x1
[1] 0x210e2870: F TerminateProcess(hProcess = 0xffffffff, uExitCode = 0xc0000409) = 0xffffffff
```

- I tried giving my system's sysWOW64 DLLs using `-r` switch, but it didn't work.
``` coffee
C:\Users\binbin\Desktop\work\binee\build>debugging_binee.exe  -r "C:\Windows\SysWOW64" ..\tests\ConsoleApplication1_x86.exe
[1] 0x224e9b20: F GetSystemTimeAsFileTime(lpSystemTimeAsFileTime = 0xb7feffe0) = 0xb7feffe0
[1] 0x224e74f0: P GetCurrentThreadId() = 0x0
Invalid Read: address = 0x30, size = 0x4, value = 0x0
```

3- I copied all the DLLs from `%windir%\SysWoW64` to `work\win10_64_syswow64\windows\system32`. Then supplied `-r` with `work\win10_64_syswow64`; **without the `windows\system32` subdirs**.
It worked, and all the tests ran well.
``` coffee
C:\Users\binbin\Desktop\work\binee\build>debugging_binee.exe  -r "C:\Users\binbin\Desktop\work\win10_64_syswow64" ..\tests\ConsoleApplication1_x86.exe
[1] 0x21b612f0: F GetSystemTimeAsFileTime(lpSystemTimeAsFileTime = 0xb7feffe0) = 0xb7feffe0
[1] 0x21b5fe70: P GetCurrentThreadId() = 0x0
...
[1] 0x20678690: P GetCurrentProcess() = 0x1
[1] 0x21b5b870: F TerminateProcess(hProcess = 0xffffffff, uExitCode = 0xc0000409) = 0xffffffff
```

## Issues:
Binee basically had 2 issues:
1- It used path concatenation instead of using the built-in `path.Join()` function.
Issue solved in 13b77a93279f99ec86d0078f862268b53ed007a0.

2- The DLL search order didn't take into consideration 32-bit and 64-bit systems and PE-files. It also concatenated `windows\system32` to the search path; so it was bound to fail if the user didn't know that.
Issue solved in 143b0a1ee442e955e318d2aa85bee60085858b9a

## Tests:
- I wrote a small script to run all the tests (except 64-bit ones), and log the output.
- Each test is run twice:
    - one time with sysWoW64 DLLs
    - another with the native 32-bit DLLs.
- Result: ✔️.
    - The results are identical (except `threads_test.exe` which gives a different output every run. This is the intended output).
- Testing scripts and results are in the attached file [pathfix_tests_for_syswow64_dlls.zip](https://github.com/MennaEssa/binee/files/5434647/pathfix_tests_for_syswow64_dlls.zip).

## Conclusion:
- Currently, running 32-bit executables should produce the same results on x32 and x64 machines (without the `-r` switch at all).
- Problems are expected in:
    - API calls that do `syscalls` and don't have full hooks implemented for them yet.
    - API functions that have different implementation in `SysWOW64 DLLs` vs. `32-bit native DLLs`.

**Comment by mmn3mm** [comment]
As discussed, in the future, all of the functions that do syscalls will be fully hooked as there is no other option anyways, so this is an issue that gets fixed step by step anyways.
The different implementation is not something we can search for as the scope is very big and we can't just search for it, so that also will be found by time and will get handled.
We should also learn more about testing in Go as it will be much more organized than using a script+ automate testing before PRs to make it the usual procedure.
Please open a PR, connect it to this issue and I will check the code and confirm it.
